### ISSUE TITLE
`Uncaught ReferenceError: DeviceMotionEvent is not defined`

### ISSUE THREAD

**Issue by lomirus** [serglider/shake-detector#2]
To produce this problem:
1. use `create-vite` and choose vanilla-ts
2. install `shake-detector`
3. add this to `main.ts`
```ts
import ShakeDetector from 'shake-detector'

const shakeDetector = new ShakeDetector({}).confirmPermissionGranted();
shakeDetector.subscribe(() => {
  console.log('Shake detected!')
}).start();
```
4. `npx vite --host` and open a link from network (note: the local link works fine)

Then it will show the error in the console:
```
Uncaught ReferenceError: DeviceMotionEvent is not defined
    at new h (utils.ts:28:19)
    at new m (index.ts:41:30)
    at main.ts:13:23
```
When I try to click into the `utils.ts:28`, it shows another error message:
```
Could not load content for http://172.17.0.1:3001/node_modules/shake-detector/src/utils.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

Versions:

```
"typescript": "^4.5.4",
"vite": "^2.8.0"
"shake-detector": "^0.3.7",
OS: Manjaro Linux x86_64
Browser: Chrome
```

**Comment by serglider** [comment]
Hi Lomirus

1. Please try

`npx vite --host --https`

The DeviceMotionEvent event is available only in secure environments.

2. Thank you for reporting. Access to potentially undefined properties should be guarded. Published v0.3.8

**Comment by lomirus** [comment]
Thanks for your fix, but how about giving more detailed information by checking the url protocol to inform user whether this problem is caused by tls issue or equipment environment?
